Dsp3/zephyr 3.2
SiemaApplications/zephyr pull request #17
Opened 2023-11-02 10:16 UTC by lbonhomme-vossloh

- The option to configure the write flash alignment  in mcuboot.
- All I2S fixes to work on STM32H743ZI
- The full-duplex integration and its Zephyr's config option.
- The resistances of TX under-run and RX overrun and their zephyr's config option.
- The IO swap option for I2S configuration

2023-11-06 09:13 UTC, smartin-vossloh commented on drivers/i2s/Kconfig.stm32
> +	  Drop data received in overrun context
@lbonhomme-vossloh  nit: missing dot at the end.

ditto below

2023-11-06 09:13 UTC, smartin-vossloh commented on drivers/i2s/i2s_ll_stm32.c
> +	/* Initiate  the block to send in underrun context*/
@lbonhomme-vossloh nit: `s/Initiate  the/Initialize the/`

2023-11-06 09:13 UTC, smartin-vossloh commented on drivers/i2s/i2s_ll_stm32.c
> +	if(i2s_cfg->options & I2S_OPT_IO_SWAP) {
@lbonhomme-vossloh missing space after keyword before `(`

2023-11-06 09:13 UTC, smartin-vossloh commented on drivers/i2s/i2s_ll_stm32.c
> +				SYS_TIMEOUT_MS(dev_data->rx.cfg.timeout));
@lbonhomme-vossloh mis-alignment

2023-11-07 11:28 UTC, smartin-vossloh commented on drivers/i2s/i2s_ll_stm32.c
> +
@lbonhomme-vossloh 1 blank line is enough ;)

2023-11-07 11:28 UTC, smartin-vossloh commented on drivers/i2s/i2s_ll_stm32.c
> +		k_sem_give(&stream->sem);
@lbonhomme-vossloh weird indentation

2023-11-07 11:28 UTC, smartin-vossloh commented on drivers/i2s/i2s_ll_stm32.c
> +		k_mem_slab_free(stream->cfg.mem_slab, &stream->last_mem_block);
@lbonhomme-vossloh weird indentation

ditto below (twice)

2023-11-07 16:06 UTC, nvincent-vossloh requested changes

2023-11-07 17:03 UTC, lbonhomme-vossloh commented on drivers/i2s/Kconfig.stm32
> +	  The board support the I2S in full-duplex mode.
This flag doesn't set the full duplex mode on I2S. The flag authorizes only to set I2S in full duplex mode.
The direction mode (RX, TX or both) is set by zephyr API and I2S_config structure.

2023-11-08 08:16 UTC, nvincent-vossloh approved these changes
ok, wait @smartin-vossloh approval before merging.

2023-11-08 10:03 UTC, nvincent-vossloh approved these changes
Looking good.

2023-11-08 10:33 UTC, smartin-vossloh approved these changes
lgtm

2023-11-08 10:50 UTC, merged